---
driver:
  name: vagrant
  vm_hostname: centos7server 

provisioner:
  name: chef_solo

platforms:
  - name: navneet-centos-7.2
 
transport:
  name: ssh  

suites:
  - name: default
    run_list:
      - recipe[my_cookbook::default]
    attributes:
